// <auto-generated />
using System;
using Fabric.Server.Contractors.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Contractors.Persistence.Migrations
{
    [DbContext(typeof(ContractorsDbContext))]
    partial class ContractorsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contractors")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("CompanyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_companies_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tenant_id_code");

                    b.HasIndex("TenantId", "CompanyNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tenant_id_company_number")
                        .HasFilter("company_number IS NOT NULL");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_companies_tenant_id_is_active");

                    b.ToTable("companies", "contractors");
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractors");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractors_tenant_id");

                    b.HasIndex("TenantId", "ArchivedAt")
                        .HasDatabaseName("ix_contractors_tenant_id_archived_at");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_contractors_tenant_id_company_id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_contractors_tenant_id_email");

                    b.ToTable("contractors", "contractors");
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.ContractorJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("PlannedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end");

                    b.Property<DateTimeOffset>("PlannedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractor_jobs");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id_company_id");

                    b.HasIndex("TenantId", "JobTypeId")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id_job_type_id");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id_location_id");

                    b.HasIndex("TenantId", "PlannedEnd")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id_planned_end");

                    b.HasIndex("TenantId", "PlannedStart")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id_planned_start");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_contractor_jobs_tenant_id_status");

                    b.ToTable("contractor_jobs", "contractors");
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.ContractorJobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_from");

                    b.Property<DateTimeOffset>("AssignedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_until");

                    b.Property<Guid>("ContractorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_id");

                    b.Property<Guid>("ContractorJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("contractor_job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contractor_job_assignments");

                    b.HasIndex("ContractorId");

                    b.HasIndex("ContractorJobId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_job_assignments_tenant_id");

                    b.HasIndex("TenantId", "AssignedFrom")
                        .HasDatabaseName("ix_contractor_job_assignments_tenant_id_assigned_from");

                    b.HasIndex("TenantId", "AssignedUntil")
                        .HasDatabaseName("ix_contractor_job_assignments_tenant_id_assigned_until");

                    b.HasIndex("TenantId", "ContractorId")
                        .HasDatabaseName("ix_contractor_job_assignments_tenant_id_contractor_id");

                    b.HasIndex("TenantId", "ContractorJobId")
                        .HasDatabaseName("ix_contractor_job_assignments_tenant_id_contractor_job_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_contractor_job_assignments_tenant_id_status");

                    b.ToTable("contractor_job_assignments", "contractors");
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.JobType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_types");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_job_types_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_job_types_tenant_id_code");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_job_types_tenant_id_is_active");

                    b.ToTable("job_types", "contractors");
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.Contractor", b =>
                {
                    b.HasOne("Fabric.Server.Contractors.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.ContractorJob", b =>
                {
                    b.HasOne("Fabric.Server.Contractors.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabric.Server.Contractors.Domain.JobType", null)
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.ContractorJobAssignment", b =>
                {
                    b.HasOne("Fabric.Server.Contractors.Domain.Contractor", null)
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabric.Server.Contractors.Domain.ContractorJob", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ContractorJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.Contractors.Domain.ContractorJob", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
