// <auto-generated />
using System;
using Fabric.Server.Sagas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Sagas.Persistence.Migrations
{
    [DbContext(typeof(SagasDbContext))]
    [Migration("20260818071847_AddContractorAssignmentAutomationMailbox")]
    partial class AddContractorAssignmentAutomationMailbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sagas")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Sagas.AccessGrantProvisioning.AccessGrantMaterializationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_grant_id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_access_grant_materialization_outcomes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grant_materialization_outcomes_tenant_id");

                    b.HasIndex("TenantId", "AccessGrantId")
                        .HasDatabaseName("ix_access_grant_materialization_outcomes_tenant_grant_id");

                    b.HasIndex("TenantId", "AccessGrantId", "AccessItemId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_grant_materialization_outcomes_tenant_grant_item_location");

                    b.ToTable("access_grant_materialization_outcomes", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.AccessGrantProvisioning.AccessGrantProvisioningSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_grant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_access_grant_provisioning_sagas");

                    b.HasIndex("AccessGrantId")
                        .IsUnique()
                        .HasDatabaseName("ix_access_grant_provisioning_sagas_access_grant_id");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_access_grant_provisioning_sagas_next_retry_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grant_provisioning_sagas_tenant_id");

                    b.ToTable("access_grant_provisioning_sagas", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.AccessGrantProvisioning.AccessGrantProvisioningSagaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_grant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_access_grant_provisioning_saga_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_access_grant_provisioning_saga_events_created_at");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_access_grant_provisioning_saga_events_next_retry_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_access_grant_provisioning_saga_events_processed_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_access_grant_provisioning_saga_events_tenant_id");

                    b.ToTable("access_grant_provisioning_saga_events", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.ContractorJobs.ContractorAssignmentAutomationMailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastKnownError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_known_error");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractor_assignment_automation_mailboxes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_assignment_automation_mailboxes_tenant_id");

                    b.HasIndex("TenantId", "AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_assignment_automation_mailboxes_tenant_id_assignment_id");

                    b.HasIndex("TenantId", "LeaseUntil")
                        .HasDatabaseName("ix_contractor_assignment_automation_mailboxes_tenant_id_lease_until");

                    b.HasIndex("TenantId", "ScheduledFor")
                        .HasDatabaseName("ix_contractor_assignment_automation_mailboxes_tenant_id_scheduled_for");

                    b.ToTable("contractor_assignment_automation_mailboxes", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.ContractorJobs.ContractorJobAccessAutomationReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastKnownError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_known_error");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractor_job_access_automation_reconciliations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_job_access_automation_reconciliations_tenant_id");

                    b.HasIndex("TenantId", "AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_job_access_automation_reconciliations_tenant_id_assignment_id");

                    b.HasIndex("TenantId", "ScheduledFor")
                        .HasDatabaseName("ix_contractor_job_access_automation_reconciliations_tenant_id_scheduled_for");

                    b.ToTable("contractor_job_access_automation_reconciliations", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.ContractorJobs.ContractorJobOnboardingReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastKnownError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_known_error");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractor_job_onboarding_reconciliations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_job_onboarding_reconciliations_tenant_id");

                    b.HasIndex("TenantId", "AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_job_onboarding_reconciliations_tenant_id_assignment_id");

                    b.HasIndex("TenantId", "ScheduledFor")
                        .HasDatabaseName("ix_contractor_job_onboarding_reconciliations_tenant_id_scheduled_for");

                    b.ToTable("contractor_job_onboarding_reconciliations", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.ContractorJobs.ContractorJobPackageRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contractor_job_package_rules");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_job_package_rules_tenant_id");

                    b.HasIndex("TenantId", "JobTypeId", "PackageId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_job_package_rules_tenant_id_job_type_package_location");

                    b.ToTable("contractor_job_package_rules", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.EmployeeLifecycle.EmployeeAccessAutomationReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("LastKnownError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_known_error");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employee_access_automation_reconciliations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_access_automation_reconciliations_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_access_automation_reconciliations_tenant_id_employee_id");

                    b.HasIndex("TenantId", "ScheduledFor")
                        .HasDatabaseName("ix_employee_access_automation_reconciliations_tenant_id_scheduled_for");

                    b.ToTable("employee_access_automation_reconciliations", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.EmployeeLifecycle.EmployeeLifecycleAutomationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DisableEmployeeOnLeave")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_employee_on_leave");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastFullReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_full_reconciled_at");

                    b.Property<DateTimeOffset?>("ReenabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reenabled_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_lifecycle_automation_settings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_lifecycle_automation_settings_tenant_id");

                    b.ToTable("employee_lifecycle_automation_settings", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.EmployeeLifecycle.OrganizationalUnitPackageRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_lifecycle_ou_package_rules");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_lifecycle_ou_package_rules_tenant_id");

                    b.HasIndex("TenantId", "OrganizationUnitId", "PackageId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_lifecycle_ou_package_rules_tenant_id_ou_package_id");

                    b.ToTable("employee_lifecycle_ou_package_rules", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.EmployeeLifecycle.PersonaPackageRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_lifecycle_persona_package_rules");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_lifecycle_persona_package_rules_tenant_id");

                    b.HasIndex("TenantId", "PersonaId", "PackageId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_lifecycle_persona_package_rules_tenant_id_persona_package_id");

                    b.ToTable("employee_lifecycle_persona_package_rules", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.Kiosk.KioskSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentInstructionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_instruction_id");

                    b.Property<string>("CurrentInstructionKind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_instruction_kind");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowInstanceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_sagas");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_sagas_session_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_kiosk_sagas_tenant_id");

                    b.HasIndex("WorkflowInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_kiosk_sagas_workflow_instance_id");

                    b.ToTable("kiosk_sagas", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.Kiosk.KioskSagaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("InstructionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("instruction_id");

                    b.Property<string>("InstructionKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("instruction_kind");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_saga_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_kiosk_saga_events_created_at");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_kiosk_saga_events_next_retry_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_kiosk_saga_events_processed_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_kiosk_saga_events_tenant_id");

                    b.ToTable("kiosk_saga_events", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.VisitorPreOnboarding.VisitorPreOnboardingSaga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccessPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_policy_id");

                    b.Property<Guid?>("ArrivalId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_id");

                    b.Property<DateTimeOffset?>("ArrivalNotificationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_notification_sent_at");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancellation_requested_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset?>("InvitationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitation_sent_at");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("qr_code");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<string>("VisitorResponseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visitor_response_status");

                    b.HasKey("Id")
                        .HasName("pk_visitor_pre_onboarding_sagas");

                    b.HasIndex("CancelledAt")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_cancelled_at");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_expired_at");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_next_retry_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_tenant_id");

                    b.HasIndex("VisitId", "InvitationId")
                        .HasDatabaseName("ix_visitor_pre_onboarding_sagas_visit_invitation");

                    b.ToTable("visitor_pre_onboarding_sagas", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.VisitorPreOnboarding.VisitorPreOnboardingSagaAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_visitor_pre_onboarding_saga_audit_entries");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_vpo_saga_audit_entries_occurred_at");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("ix_vpo_saga_audit_entries_saga_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_visitor_pre_onboarding_saga_audit_entries_tenant_id");

                    b.ToTable("visitor_pre_onboarding_saga_audit_entries", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.VisitorPreOnboarding.VisitorPreOnboardingSagaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("GraceEndMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("grace_end_minutes");

                    b.Property<int>("GraceStartMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("grace_start_minutes");

                    b.Property<Guid?>("QrCredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_credential_type_id");

                    b.Property<bool>("SendArrivalNotificationToHost")
                        .HasColumnType("boolean")
                        .HasColumnName("send_arrival_notification_to_host");

                    b.Property<bool>("SendCancellationNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("send_cancellation_notification");

                    b.Property<bool>("SendConfirmNotificationToHost")
                        .HasColumnType("boolean")
                        .HasColumnName("send_confirm_notification_to_host");

                    b.Property<bool>("SendRelocationNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("send_relocation_notification");

                    b.Property<bool>("SendRescheduleNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("send_reschedule_notification");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("UseCustomArrivalNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("use_custom_arrival_notification");

                    b.Property<bool>("UseCustomCancellationNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("use_custom_cancellation_notification");

                    b.Property<bool>("UseCustomConfirmNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("use_custom_confirm_notification");

                    b.Property<bool>("UseCustomInviteNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("use_custom_invite_notification");

                    b.Property<bool>("UseCustomRelocationNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("use_custom_relocation_notification");

                    b.Property<bool>("UseCustomRescheduleNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("use_custom_reschedule_notification");

                    b.HasKey("Id")
                        .HasName("pk_visitor_pre_onboarding_saga_configs");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_visitor_pre_onboarding_saga_configs_tenant_id");

                    b.ToTable("visitor_pre_onboarding_saga_configs", "sagas", t =>
                        {
                            t.HasCheckConstraint("ck_vpo_config_arrival_notification_all_or_null", "(custom_arrival_notification_subject IS NULL) = (custom_arrival_notification_body IS NULL)");

                            t.HasCheckConstraint("ck_vpo_config_cancellation_notification_all_or_null", "(custom_cancellation_notification_subject IS NULL) = (custom_cancellation_notification_body IS NULL)");

                            t.HasCheckConstraint("ck_vpo_config_confirm_notification_all_or_null", "(custom_confirm_notification_subject IS NULL) = (custom_confirm_notification_body IS NULL)");

                            t.HasCheckConstraint("ck_vpo_config_invite_notification_all_or_null", "(custom_invite_notification_subject IS NULL) = (custom_invite_notification_body IS NULL)");

                            t.HasCheckConstraint("ck_vpo_config_relocation_notification_all_or_null", "(custom_relocation_notification_subject IS NULL) = (custom_relocation_notification_body IS NULL)");

                            t.HasCheckConstraint("ck_vpo_config_reschedule_notification_all_or_null", "(custom_reschedule_notification_subject IS NULL) = (custom_reschedule_notification_body IS NULL)");
                        });
                });

            modelBuilder.Entity("Fabric.Server.Sagas.VisitorPreOnboarding.VisitorPreOnboardingSagaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArrivalId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visitor_pre_onboarding_saga_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_vpo_saga_events_created_at");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("ix_vpo_saga_events_next_retry_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_vpo_saga_events_processed_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_visitor_pre_onboarding_saga_events_tenant_id");

                    b.ToTable("visitor_pre_onboarding_saga_events", "sagas");
                });

            modelBuilder.Entity("Fabric.Server.Sagas.VisitorPreOnboarding.VisitorPreOnboardingSagaConfig", b =>
                {
                    b.OwnsOne("Fabric.Server.Sagas.VisitorPreOnboarding.CustomNotification", "CustomArrivalNotification", b1 =>
                        {
                            b1.Property<Guid>("VisitorPreOnboardingSagaConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_arrival_notification_body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_arrival_notification_subject");

                            b1.HasKey("VisitorPreOnboardingSagaConfigId");

                            b1.ToTable("visitor_pre_onboarding_saga_configs", "sagas");

                            b1.WithOwner()
                                .HasForeignKey("VisitorPreOnboardingSagaConfigId");
                        });

                    b.OwnsOne("Fabric.Server.Sagas.VisitorPreOnboarding.CustomNotification", "CustomCancellationNotification", b1 =>
                        {
                            b1.Property<Guid>("VisitorPreOnboardingSagaConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_cancellation_notification_body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_cancellation_notification_subject");

                            b1.HasKey("VisitorPreOnboardingSagaConfigId");

                            b1.ToTable("visitor_pre_onboarding_saga_configs", "sagas");

                            b1.WithOwner()
                                .HasForeignKey("VisitorPreOnboardingSagaConfigId");
                        });

                    b.OwnsOne("Fabric.Server.Sagas.VisitorPreOnboarding.CustomNotification", "CustomConfirmNotification", b1 =>
                        {
                            b1.Property<Guid>("VisitorPreOnboardingSagaConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_confirm_notification_body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_confirm_notification_subject");

                            b1.HasKey("VisitorPreOnboardingSagaConfigId");

                            b1.ToTable("visitor_pre_onboarding_saga_configs", "sagas");

                            b1.WithOwner()
                                .HasForeignKey("VisitorPreOnboardingSagaConfigId");
                        });

                    b.OwnsOne("Fabric.Server.Sagas.VisitorPreOnboarding.CustomNotification", "CustomInviteNotification", b1 =>
                        {
                            b1.Property<Guid>("VisitorPreOnboardingSagaConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_invite_notification_body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_invite_notification_subject");

                            b1.HasKey("VisitorPreOnboardingSagaConfigId");

                            b1.ToTable("visitor_pre_onboarding_saga_configs", "sagas");

                            b1.WithOwner()
                                .HasForeignKey("VisitorPreOnboardingSagaConfigId");
                        });

                    b.OwnsOne("Fabric.Server.Sagas.VisitorPreOnboarding.CustomNotification", "CustomRelocationNotification", b1 =>
                        {
                            b1.Property<Guid>("VisitorPreOnboardingSagaConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_relocation_notification_body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_relocation_notification_subject");

                            b1.HasKey("VisitorPreOnboardingSagaConfigId");

                            b1.ToTable("visitor_pre_onboarding_saga_configs", "sagas");

                            b1.WithOwner()
                                .HasForeignKey("VisitorPreOnboardingSagaConfigId");
                        });

                    b.OwnsOne("Fabric.Server.Sagas.VisitorPreOnboarding.CustomNotification", "CustomRescheduleNotification", b1 =>
                        {
                            b1.Property<Guid>("VisitorPreOnboardingSagaConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_reschedule_notification_body");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("custom_reschedule_notification_subject");

                            b1.HasKey("VisitorPreOnboardingSagaConfigId");

                            b1.ToTable("visitor_pre_onboarding_saga_configs", "sagas");

                            b1.WithOwner()
                                .HasForeignKey("VisitorPreOnboardingSagaConfigId");
                        });

                    b.Navigation("CustomArrivalNotification");

                    b.Navigation("CustomCancellationNotification");

                    b.Navigation("CustomConfirmNotification");

                    b.Navigation("CustomInviteNotification");

                    b.Navigation("CustomRelocationNotification");

                    b.Navigation("CustomRescheduleNotification");
                });
#pragma warning restore 612, 618
        }
    }
}
