// <auto-generated />
using System;
using Fabric.Server.Printing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Printing.Persistence.Migrations
{
    [DbContext(typeof(PrintingDbContext))]
    [Migration("20260810095710_AddPrintDesignDefaultRenderProfile")]
    partial class AddPrintDesignDefaultRenderProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("printing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Printing.Domain.PrintDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultRenderProfile")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DesignJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Dpi")
                        .HasColumnType("integer");

                    b.Property<double>("MediaHeight")
                        .HasColumnType("double precision");

                    b.Property<string>("MediaLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MediaOrientation")
                        .HasColumnType("integer");

                    b.Property<double>("MediaWidth")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SurfaceKind")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaLabel");

                    b.HasIndex("SurfaceKind");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_print_designs_tenant_id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("print_designs", "printing");
                });
#pragma warning restore 612, 618
        }
    }
}
