// <auto-generated />
using System;
using Fabric.Server.CredentialManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.CredentialManagement.Persistence.Migrations
{
    [DbContext(typeof(CredentialManagementDbContext))]
    [Migration("20260729053605_AddCredentialTypeQrIdentifierFormatting")]
    partial class AddCredentialTypeQrIdentifierFormatting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("credential_management")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_type_id");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration_kind");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_text");

                    b.Property<Guid?>("RequestedByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_identity_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("CredentialTypeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credentials_tenant_id");

                    b.HasIndex("TenantId", "IdentityId")
                        .HasDatabaseName("ix_credentials_tenant_id_identity_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_credentials_tenant_id_status");

                    b.HasIndex("TenantId", "CredentialTypeId", "Identifier")
                        .HasDatabaseName("ix_credentials_tenant_id_credential_type_identifier");

                    b.HasIndex("TenantId", "SourceKind", "SourceId")
                        .HasDatabaseName("ix_credentials_tenant_id_source");

                    b.ToTable("credentials", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialRange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CredentialTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("NextCandidateNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_candidate_number");

                    b.Property<long>("RangeStart")
                        .HasColumnType("bigint")
                        .HasColumnName("range_start");

                    b.Property<long>("RangeStop")
                        .HasColumnType("bigint")
                        .HasColumnName("range_stop");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_credential_ranges");

                    b.HasIndex("CredentialTypeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_ranges_tenant_id");

                    b.HasIndex("TenantId", "CredentialTypeId")
                        .HasDatabaseName("ix_credential_ranges_tenant_id_credential_type_id");

                    b.ToTable("credential_ranges", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("CredentialRangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_range_id");

                    b.Property<DateTimeOffset>("LastStateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_state_changed_at");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("ReservationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_expires_at");

                    b.Property<DateTimeOffset?>("ReusableFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reusable_from");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_credential_slots");

                    b.HasIndex("CredentialRangeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_slots_tenant_id");

                    b.HasIndex("TenantId", "CredentialId")
                        .HasDatabaseName("ix_credential_slots_tenant_id_credential_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_credential_slots_tenant_id_status");

                    b.HasIndex("TenantId", "CredentialRangeId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_slots_tenant_id_range_number");

                    b.ToTable("credential_slots", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllocationMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("allocation_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdentifierNumberLength")
                        .HasColumnType("integer")
                        .HasColumnName("identifier_number_length");

                    b.Property<string>("IdentifierPaddingCharacter")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("identifier_padding_character");

                    b.Property<string>("IdentifierPaddingDirection")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identifier_padding_direction");

                    b.Property<string>("IdentifierPrefix")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_prefix");

                    b.Property<string>("IdentifierSuffix")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier_suffix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("NearLimitThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("near_limit_threshold");

                    b.Property<TimeSpan>("RecycleGracePeriod")
                        .HasColumnType("interval")
                        .HasColumnName("recycle_grace_period");

                    b.Property<string>("RecyclePolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recycle_policy");

                    b.Property<bool>("RequiresConfirmedPacsRevocation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_confirmed_pacs_revocation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("technology");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credential_types");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_types_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_types_tenant_id_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_credential_types_tenant_id_status");

                    b.ToTable("credential_types", "credential_management");
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.Credential", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialType", null)
                        .WithMany()
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialRange", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialType", null)
                        .WithMany("Ranges")
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialSlot", b =>
                {
                    b.HasOne("Fabric.Server.CredentialManagement.Domain.CredentialRange", null)
                        .WithMany()
                        .HasForeignKey("CredentialRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Server.CredentialManagement.Domain.CredentialType", b =>
                {
                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
