// <auto-generated />
using System;
using Fabric.Server.Learning.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Learning.Persistence.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    [Migration("20260819104912_AddLearningContext")]
    partial class AddLearningContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Learning.Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("completion_status");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("CourseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_version_id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsScored")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scored");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("score");

                    b.Property<decimal?>("ScoreScaled")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("score_scaled");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SuccessStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("success_status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_attempts_tenant_id");

                    b.HasIndex("TenantId", "EnrollmentId", "StartedAt")
                        .HasDatabaseName("ix_attempts_tenant_id_enrollment_id_started_at");

                    b.ToTable("attempts", "learning");
                });

            modelBuilder.Entity("Fabric.Server.Learning.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_courses_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_tenant_id_code");

                    b.ToTable("courses", "learning");
                });

            modelBuilder.Entity("Fabric.Server.Learning.Domain.CourseSco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_version_id");

                    b.Property<string>("LaunchUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("launch_url");

                    b.Property<int>("ManifestOrder")
                        .HasColumnType("integer")
                        .HasColumnName("manifest_order");

                    b.Property<decimal?>("MasteryScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("mastery_score");

                    b.Property<string>("ResourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resource_path");

                    b.Property<string>("ScoIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sco_identifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_course_scos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_course_scos_tenant_id");

                    b.HasIndex("TenantId", "CourseVersionId", "ManifestOrder")
                        .HasDatabaseName("ix_course_scos_tenant_id_course_version_id_manifest_order");

                    b.ToTable("course_scos", "learning");
                });

            modelBuilder.Entity("Fabric.Server.Learning.Domain.CourseVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EmitsScore")
                        .HasColumnType("boolean")
                        .HasColumnName("emits_score");

                    b.Property<string>("ManifestChecksum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manifest_checksum");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ScormVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scorm_version");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("storage_path");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_course_versions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_course_versions_tenant_id");

                    b.HasIndex("TenantId", "CourseId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_course_versions_tenant_id_course_id_version_number");

                    b.ToTable("course_versions", "learning");
                });

            modelBuilder.Entity("Fabric.Server.Learning.Domain.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_identity_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledByIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_identity_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_attempt_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid?>("LatestAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_attempt_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_enrollments_tenant_id");

                    b.HasIndex("TenantId", "CourseId", "IdentityId", "Status")
                        .HasDatabaseName("ix_enrollments_tenant_id_course_id_identity_id_status");

                    b.ToTable("enrollments", "learning");
                });

            modelBuilder.Entity("Fabric.Server.Learning.Domain.LaunchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("CourseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid?>("ScoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sco_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_launch_sessions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_launch_sessions_tenant_id");

                    b.HasIndex("TenantId", "Token")
                        .IsUnique()
                        .HasDatabaseName("ix_launch_sessions_tenant_id_token");

                    b.ToTable("launch_sessions", "learning");
                });

            modelBuilder.Entity("Fabric.Server.Learning.Domain.ScormProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<string>("BookmarkLocation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bookmark_location");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("completion_status");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("CourseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_version_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("LastCommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_committed_at");

                    b.Property<string>("RawCmiData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_cmi_data");

                    b.Property<Guid?>("ScoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sco_id");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("score");

                    b.Property<decimal?>("ScoreScaled")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("score_scaled");

                    b.Property<string>("ScormVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scorm_version");

                    b.Property<string>("SessionTime")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_time");

                    b.Property<string>("SuccessStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("success_status");

                    b.Property<string>("SuspendData")
                        .HasMaxLength(32000)
                        .HasColumnType("character varying(32000)")
                        .HasColumnName("suspend_data");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_scorm_progress");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scorm_progress_tenant_id");

                    b.HasIndex("TenantId", "AttemptId", "ScoId")
                        .HasDatabaseName("ix_scorm_progress_tenant_id_attempt_id_sco_id");

                    b.ToTable("scorm_progress", "learning");
                });
#pragma warning restore 612, 618
        }
    }
}
