using System.Text.Json;
using System.Text.Json.Serialization;
using Fabric.Hardware.Desfire.Encoding.Models;
using Fabric.Hardware.Desfire.Encoding.Specifications;
using Fabric.Hardware.Desfire.Protocol;
using Fabric.Server.Core;
using Fabric.Server.Desfire.Contracts;
using Fabric.Server.Desfire.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Fabric.Server.Desfire;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
[JsonSerializable(typeof(BadgeJobKind))]
[JsonSerializable(typeof(BadgeJobStatus))]
[JsonSerializable(typeof(BadgeBatchStatus))]
[JsonSerializable(typeof(BadgeJobMode))]
[JsonSerializable(typeof(DesfireVariableProviderKind))]
[JsonSerializable(typeof(DesfireVariableFormatKind))]
[JsonSerializable(typeof(WiegandParityKind))]
[JsonSerializable(typeof(WiegandFieldSourceKind))]
[JsonSerializable(typeof(KeyDiversificationAlgorithm))]
[JsonSerializable(typeof(DiversificationInputOptions))]
[JsonSerializable(typeof(KeyType))]
[JsonSerializable(typeof(TemplateSpecification))]
[JsonSerializable(typeof(PiccSpecification))]
[JsonSerializable(typeof(ApplicationSpecification))]
[JsonSerializable(typeof(FileSpecification))]
[JsonSerializable(typeof(DiversificationInput))]
[JsonSerializable(typeof(ChipDesignResponse))]
[JsonSerializable(typeof(CreateChipDesignRequest))]
[JsonSerializable(typeof(UpdateChipDesignRequest))]
[JsonSerializable(typeof(TransformationResponse))]
[JsonSerializable(typeof(CreateTransformationRequest))]
[JsonSerializable(typeof(UpdateTransformationRequest))]
[JsonSerializable(typeof(TransformationPlanResponse))]
[JsonSerializable(typeof(TransformationPlanOperationResponse))]
[JsonSerializable(typeof(TransformationVariableConfigRequest))]
[JsonSerializable(typeof(TransformationVariableConfigRequest[]))]
[JsonSerializable(typeof(TransformationVariableKind))]
[JsonSerializable(typeof(SystemVariableProviderKind))]
[JsonSerializable(typeof(SystemProviderResponse))]
[JsonSerializable(typeof(CreateSystemProviderRequest))]
[JsonSerializable(typeof(EncoderResponse))]
[JsonSerializable(typeof(CreateEncoderRequest))]
[JsonSerializable(typeof(UpdateEncoderRequest))]
[JsonSerializable(typeof(KeyDiversificationStrategyResponse))]
[JsonSerializable(typeof(CreateKeyDiversificationStrategyRequest))]
[JsonSerializable(typeof(UpdateKeyDiversificationStrategyRequest))]
[JsonSerializable(typeof(KeyGroupResponse))]
[JsonSerializable(typeof(CreateKeyGroupRequest))]
[JsonSerializable(typeof(UpdateKeyGroupRequest))]
[JsonSerializable(typeof(BadgeBatchResponse))]
[JsonSerializable(typeof(CreateBadgeBatchRequest))]
[JsonSerializable(typeof(BadgeBatchJobSummary))]
[JsonSerializable(typeof(BadgeJobResponse))]
[JsonSerializable(typeof(CreateBadgeJobRequest))]
[JsonSerializable(typeof(EncodingVariableRequest))]
[JsonSerializable(typeof(EncodingVariableRequest[]))]
[JsonSerializable(typeof(VariableProviderRequest))]
[JsonSerializable(typeof(VariableFormatRequest))]
[JsonSerializable(typeof(GenericWiegandFormatRequest))]
[JsonSerializable(typeof(WiegandFieldRequest))]
[JsonSerializable(typeof(WiegandParityRequest))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Page<ChipDesignResponse>))]
[JsonSerializable(typeof(Page<TransformationResponse>))]
[JsonSerializable(typeof(Page<SystemProviderResponse>))]
[JsonSerializable(typeof(Page<EncoderResponse>))]
[JsonSerializable(typeof(Page<KeyDiversificationStrategyResponse>))]
[JsonSerializable(typeof(Page<KeyGroupResponse>))]
[JsonSerializable(typeof(Page<BadgeJobResponse>))]
[JsonSerializable(typeof(Page<BadgeBatchResponse>))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(ProblemDetails))]
internal sealed partial class DesfireJsonSerializerContext : JsonSerializerContext;
