// <auto-generated />
using System;
using Fabric.Server.Requirements.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Requirements.Persistence.Migrations
{
    [DbContext(typeof(RequirementsDbContext))]
    [Migration("20260814133400_AddRequirementsContext")]
    partial class AddRequirementsContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("requirements")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ContractorJobRequirementPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnforcementZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("enforcement_zone_id");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocking");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contractor_job_requirement_policies");

                    b.HasIndex("EnforcementZoneId");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contractor_job_requirement_policies_tenant_id");

                    b.HasIndex("TenantId", "EnforcementZoneId", "JobTypeId", "RequirementDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_job_requirement_policies_tenant_id_zone_jobtype_requirement");

                    b.ToTable("contractor_job_requirement_policies", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.EnforcementZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_enforcement_zones");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_enforcement_zones_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_enforcement_zones_tenant_id_code");

                    b.ToTable("enforcement_zones", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.EnforcementZoneAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnforcementZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("enforcement_zone_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_enforcement_zone_access_policies");

                    b.HasIndex("EnforcementZoneId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_enforcement_zone_access_policies_tenant_id");

                    b.HasIndex("TenantId", "EnforcementZoneId", "AccessItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_enforcement_zone_access_policies_tenant_id_zone_access_item");

                    b.ToTable("enforcement_zone_access_policies", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.EnforcementZoneLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnforcementZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("enforcement_zone_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_enforcement_zone_locations");

                    b.HasIndex("EnforcementZoneId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_enforcement_zone_locations_tenant_id");

                    b.HasIndex("TenantId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_enforcement_zone_locations_tenant_id_location_id");

                    b.HasIndex("TenantId", "EnforcementZoneId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_enforcement_zone_locations_tenant_id_zone_location");

                    b.ToTable("enforcement_zone_locations", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ProjectedZoneAccessAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnforcementZoneAccessPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("enforcement_zone_access_policy_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ZoneComplianceId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_compliance_id");

                    b.HasKey("Id")
                        .HasName("pk_projected_zone_access_assignments");

                    b.HasIndex("EnforcementZoneAccessPolicyId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_projected_zone_access_assignments_tenant_id");

                    b.HasIndex("ZoneComplianceId");

                    b.HasIndex("TenantId", "ZoneComplianceId", "EnforcementZoneAccessPolicyId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_projected_zone_access_assignments_tenant_id_zone_compliance_policy_location");

                    b.ToTable("projected_zone_access_assignments", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.RequirementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EvaluatorKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evaluator_kind");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_requirement_definitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_requirement_definitions_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_requirement_definitions_tenant_id_code");

                    b.ToTable("requirement_definitions", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.RequirementEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evidence_kind");

                    b.Property<string>("FileName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_requirement_evidence");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_requirement_evidence_tenant_id");

                    b.HasIndex("TenantId", "IdentityId", "RequirementDefinitionId")
                        .HasDatabaseName("ix_requirement_evidence_tenant_id_identity_requirement");

                    b.ToTable("requirement_evidence", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculatedStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calculated_status");

                    b.Property<Guid>("EnforcementZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("enforcement_zone_id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<string>("ReasonSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_summary");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_kind");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_zone_compliances");

                    b.HasIndex("EnforcementZoneId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_zone_compliances_tenant_id");

                    b.HasIndex("TenantId", "IdentityId", "EnforcementZoneId")
                        .IsUnique()
                        .HasDatabaseName("ix_zone_compliances_tenant_id_identity_zone");

                    b.ToTable("zone_compliances", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneComplianceRequirementResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EvidenceKind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evidence_kind");

                    b.Property<string>("EvidenceReference")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("evidence_reference");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<Guid>("ZoneComplianceId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_compliance_id");

                    b.HasKey("Id")
                        .HasName("pk_zone_compliance_requirement_results");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_zone_compliance_requirement_results_tenant_id");

                    b.HasIndex("ZoneComplianceId")
                        .HasDatabaseName("ix_zone_compliance_requirement_results_zone_compliance_id");

                    b.ToTable("zone_compliance_requirement_results", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneRequirementPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnforcementZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("enforcement_zone_id");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocking");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_kind");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_zone_requirement_policies");

                    b.HasIndex("EnforcementZoneId");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_zone_requirement_policies_tenant_id");

                    b.HasIndex("TenantId", "EnforcementZoneId", "RequirementDefinitionId", "SubjectKind")
                        .IsUnique()
                        .HasDatabaseName("ix_zone_requirement_policies_tenant_id_zone_requirement_subject");

                    b.ToTable("zone_requirement_policies", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ContractorJobRequirementPolicy", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.EnforcementZone", null)
                        .WithMany()
                        .HasForeignKey("EnforcementZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contractor_job_requirement_policies_enforcement_zones_enforcement_zone_id");

                    b.HasOne("Fabric.Server.Requirements.Domain.RequirementDefinition", null)
                        .WithMany()
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contractor_job_requirement_policies_requirement_definitions_requirement_definition_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.EnforcementZoneAccessPolicy", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.EnforcementZone", null)
                        .WithMany()
                        .HasForeignKey("EnforcementZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enforcement_zone_access_policies_enforcement_zones_enforcement_zone_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.EnforcementZoneLocation", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.EnforcementZone", null)
                        .WithMany()
                        .HasForeignKey("EnforcementZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enforcement_zone_locations_enforcement_zones_enforcement_zone_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ProjectedZoneAccessAssignment", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.EnforcementZoneAccessPolicy", null)
                        .WithMany()
                        .HasForeignKey("EnforcementZoneAccessPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projected_zone_access_assignments_enforcement_zone_access_policies_policy_id");

                    b.HasOne("Fabric.Server.Requirements.Domain.ZoneCompliance", null)
                        .WithMany()
                        .HasForeignKey("ZoneComplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projected_zone_access_assignments_zone_compliances_zone_compliance_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.RequirementEvidence", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.RequirementDefinition", null)
                        .WithMany()
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requirement_evidence_requirement_definitions_requirement_definition_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneCompliance", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.EnforcementZone", null)
                        .WithMany()
                        .HasForeignKey("EnforcementZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_compliances_enforcement_zones_enforcement_zone_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneComplianceRequirementResult", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.RequirementDefinition", null)
                        .WithMany()
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_compliance_requirement_results_requirement_definitions_requirement_definition_id");

                    b.HasOne("Fabric.Server.Requirements.Domain.ZoneCompliance", null)
                        .WithMany("RequirementResults")
                        .HasForeignKey("ZoneComplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_compliance_requirement_results_zone_compliances_zone_compliance_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneRequirementPolicy", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.EnforcementZone", null)
                        .WithMany()
                        .HasForeignKey("EnforcementZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_requirement_policies_enforcement_zones_enforcement_zone_id");

                    b.HasOne("Fabric.Server.Requirements.Domain.RequirementDefinition", null)
                        .WithMany()
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zone_requirement_policies_requirement_definitions_requirement_definition_id");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.ZoneCompliance", b =>
                {
                    b.Navigation("RequirementResults");
                });
#pragma warning restore 612, 618
        }
    }
}
