// <auto-generated />
using System;
using Fabric.Server.Requirements.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fabric.Server.Requirements.Persistence.Migrations
{
    [DbContext(typeof(RequirementsDbContext))]
    partial class RequirementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("requirements")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.LocationJobRequirementPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocking");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_location_job_requirement_policies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_location_job_requirement_policies_tenant_id");

                    b.HasIndex("TenantId", "LocationId", "JobTypeId", "RequirementDefinitionId")
                        .HasDatabaseName("ix_location_job_requirement_policies_tenant_id_location_id_job_type_id_requirement_definition_id");

                    b.ToTable("location_job_requirement_policies", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.LocationRequirementPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocking");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_kind");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_location_requirement_policies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_location_requirement_policies_tenant_id");

                    b.HasIndex("TenantId", "LocationId", "RequirementDefinitionId", "SubjectKind")
                        .HasDatabaseName("ix_location_requirement_policies_tenant_id_location_id_requirement_definition_id_subject_kind");

                    b.ToTable("location_requirement_policies", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.RequirementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("EvaluatorKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evaluator_kind");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_requirement_definitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_requirement_definitions_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_requirement_definitions_tenant_id_code");

                    b.ToTable("requirement_definitions", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.RequirementEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evidence_kind");

                    b.Property<string>("FileName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sensitive");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_definition_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_requirement_evidence");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_requirement_evidence_tenant_id");

                    b.HasIndex("TenantId", "IdentityId", "RequirementDefinitionId")
                        .HasDatabaseName("ix_requirement_evidence_tenant_id_identity_requirement");

                    b.ToTable("requirement_evidence", "requirements");
                });

            modelBuilder.Entity("Fabric.Server.Requirements.Domain.RequirementEvidence", b =>
                {
                    b.HasOne("Fabric.Server.Requirements.Domain.RequirementDefinition", null)
                        .WithMany()
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requirement_evidence_requirement_definitions_requirement_definition_id");
                });
#pragma warning restore 612, 618
        }
    }
}
