<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fabric.Keycloak</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="GenerateKeycloakClient">
    <MakeDir Directories="$(ProjectDir)Generated" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="$(NSwagExe_Net100) run nswag.json" />
  </Target>
</Project>
